In [1]:
# Numpy Assignment

In [2]:
import numpy as np

In [3]:
# Q.1

In [4]:
arr = np.array([1, 7, 13, 105])
print(arr)
print(f"Total memory in bytes:{arr.nbytes}")

[  1   7  13 105]
Total memory in bytes:32


In [6]:
# Q.3

In [7]:
a1 = np.zeros(10)
print(a1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
a2 = np.ones(10)
print(a2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
a3 = a2*5
print(a3)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [16]:
print(a3*2)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [17]:
print(a3*4)

[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]


In [18]:
print(a3*10)

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [19]:
# Q.4

In [23]:
n1 = np.arange(30,71)
print(n1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
# Q.5

In [24]:
n2 = np.arange(50,96)
print(n2)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [ ]:
# Q.6

In [25]:
n3 = np.arange(20,81,2)
print(n3)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [ ]:
# Q.7

In [26]:
n4 = np.arange(21,80,2)
print(n4)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [ ]:
# Q.8

In [27]:
n5 = np.random.randint(10,40,15)
print(n5)

[24 20 25 20 25 35 30 30 28 32 23 31 21 28 34]


In [ ]:
# Q.9

In [28]:
n5 = np.random.randint(30,50,10)
print(n5)

[30 35 48 47 46 41 33 30 48 37]


In [ ]:
# Q.10

In [29]:
n5 = np.random.randint(50,90,20)
print(n5)

[65 88 65 59 84 60 60 69 67 66 67 55 70 53 78 85 78 63 74 50]


In [ ]:
# Q.11

In [31]:
a1 = np.array([10,20,30,40])
a2 = np.array([1,2,3,4])
print(a1)
print(a2)
print(a1+a2)
print(a1*a2)
print(a1-a2)
print(a1/a2)

[10 20 30 40]
[1 2 3 4]
[11 22 33 44]
[ 10  40  90 160]
[ 9 18 27 36]
[10. 10. 10. 10.]


In [ ]:
# Q.12

In [37]:
n1 = np.arange(10,22)
n1 = n1.reshape(3,4)
print(n1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [ ]:
# Q.13

In [42]:
n2 = np.eye(3)
print(n2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Q.14

In [44]:
n1 = np.arange(10,22).reshape(3,4)
print("Given Matrix :")
print(n1)
print(f"No. of rows and columns in given matrix : {n1.shape}")


Given Matrix :
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
No. of rows and columns in given matrix : (3, 4)


In [ ]:
# Q.15

In [45]:
a1 = np.diag([1,2,3,4,5])
print(a1)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
# Q.18

In [48]:
l1 = [10,20,30,40]
print(f"list : {l1}")
a1 = np.array(l1)
print(f"One-dimensional numpy array : {a1}")
print(f"NDIM = {a1.ndim}")

list : [10, 20, 30, 40]
One-dimensional numpy array : [10 20 30 40]
NDIM = 1


In [ ]:
# Q.19

In [49]:
s1 = np.arange(2,11).reshape(3,3)
print(s1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
# Q.20

In [50]:
s2 = np.arange(12,38)
print(s2)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [ ]:
# Q.21

In [52]:
s3 = np.arange(1,5)
print(f"Original array : {s3}")
s3 = s3[::-1]
print(f"Reverse array : {s3}")

Original array : [1 2 3 4]
Reverse array : [4 3 2 1]


In [ ]:
# Q.22

In [61]:
n2 = np.array([11,22,33])
print(n2)
print(f"DTYPE = {n2.dtype}")
n2 = np.array([11,22,33],dtype=np.float16)
print(n2)
print(f"DTYPE = {n2.dtype}")

[11 22 33]
DTYPE = int64
[11. 22. 33.]
DTYPE = float16


In [ ]:
# Q.23

In [63]:
l2 = [10,20,30,40,50,60,70,80,90]
print(f"list : {l2}")
a2 = np.array(l2)
print(f"Array : {a2}")


list : [10, 20, 30, 40, 50, 60, 70, 80, 90]
Array : [10 20 30 40 50 60 70 80 90]


In [ ]:
# Q.24

In [5]:
a1 = np.array([11,22,33,44,55])
a2 = np.remainder(a1,5)
print(a2)

[1 2 3 4 0]


In [6]:
# Q.25

In [7]:
a1 = np.arange(20,50)
print(a1)
a2 = np.remainder(a1,3)
print(f"Rema"a2)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
